---
- name: VMware Tools Upgrade
  hosts: ubuntu_servers
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure prerequisites are installed
      apt:
        name:
          - open-vm-tools
          - open-vm-tools-desktop
        state: latest
        update_cache: yes

    - name: Check current VMware Tools version
      shell: vmware-toolbox-cmd -v
      register: vmware_tools_version
      ignore_errors: yes

    - name: Display current VMware Tools version
      debug:
        msg: "Current VMware Tools version: {{ vmware_tools_version.stdout }}"

    - name: Stop VMware Tools service
      service:
        name: open-vm-tools
        state: stopped

    - name: Remove existing VMware Tools packages
      apt:
        name:
          - open-vm-tools
          - open-vm-tools-desktop
        state: absent

    - name: Install the latest VMware Tools
      apt:
        name:
          - open-vm-tools
          - open-vm-tools-desktop
        state: latest

    - name: Start VMware Tools service
      service:
        name: open-vm-tools
        state: started

    - name: Check new VMware Tools version
      shell: vmware-toolbox-cmd -v
      register: new_vmware_tools_version
      ignore_errors: yes

    - name: Display new VMware Tools version
      debug:
        msg: "New VMware Tools version: {{ new_vmware_tools_version.stdout }}"

    - name: Reboot the server if required
      reboot:
        msg: "Reboot initiated by Ansible for VMware Tools upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Wait for the server to come back up
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      become: no

    - name: Perform post-reboot tasks (if any)
      debug:
        msg: "Server has rebooted successfully"

